version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myUser
      POSTGRES_PASSWORD: myPassword
      POSTGRES_DB: myDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/myDB
      SPRING_DATASOURCE_USERNAME: myUser
      SPRING_DATASOURCE_PASSWORD: myPassword
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
